# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Champrep < Formula
  desc "The official ChamPrep command-line tool."
  homepage "https://cli.champrep.com"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.champrep.com/download/v0.1.4/champrep_0.1.4_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b7cfb5b5c22f6f9f9c756a6e492e89df3ef429794128a5f57cf5cc7667177254"

      define_method(:install) do
        bin.install "champrep"
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.champrep.com/download/v0.1.4/champrep_0.1.4_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0a2520b039c613a3a2f5eb87c82abcbdc522f3016c00052621ddc81667c07b00"

      define_method(:install) do
        bin.install "champrep"
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.champrep.com/download/v0.1.4/champrep_0.1.4_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2041da2e7e5f60d89d06d55e6d734a6ae6c1460407541bdf09a9b25fa5736a40"
      define_method(:install) do
        bin.install "champrep"
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.champrep.com/download/v0.1.4/champrep_0.1.4_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "29c406c6b387391c5f3c23e5bc20e19da03d1bcf0b3ce504c2ee69b25c53a1e2"
      define_method(:install) do
        bin.install "champrep"
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
  end

  test do
    system "#{bin}/champrep", "--version"
  end
end
