# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Champrep < Formula
  desc "The official CHAMPREP command-line tool."
  homepage "https://cli.champrep.com"
  version "0.3.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.champrep.com/download/v0.3.6/champrep_0.3.6_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cb8bd57e6b57357ba4b8056acb9761a45afc1e30c30cefe5d394843df49c35d0"

      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.champrep.com/download/v0.3.6/champrep_0.3.6_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "97f8a1b3a93457fefc517ce5f2080def5e5e70dcc370c2caa4ebd64bd7a7266d"

      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.champrep.com/download/v0.3.6/champrep_0.3.6_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c1c9001b3f62070f2e8f68a2eda474efbbfd37f6c2645c3a2be1ec06c9db1403"
      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.champrep.com/download/v0.3.6/champrep_0.3.6_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "895a8b3832c7af05156e905ad0627c50267c94916b87b3d30a43ef413dbc9ac3"
      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
  end

  test do
    system "#{bin}/champrep", "--version"
  end
end
