# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Champrep < Formula
  desc "The official CHAMPREP command-line tool."
  homepage "https://cli.champrep.com"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.champrep.com/download/v0.2.0/champrep_0.2.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e76705c48c8d935475c2f2ae59533239e96f69fbf09b09ed991f42c1f1f97262"

      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.champrep.com/download/v0.2.0/champrep_0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "550dd01ce183398161478d809a9bf635bc91b4740c7f96785e423aaa3d0a941d"

      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.champrep.com/download/v0.2.0/champrep_0.2.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "29e29a0d7136de91a98a28abcbe7dc49b643c91fd707d01886a67663ab5e83fc"
      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.champrep.com/download/v0.2.0/champrep_0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "eb7d1b6b2938da387a4a7e900a21d77fd7401cc6c6a979258e568a78a928002e"
      define_method(:install) do
        bin.install "champrep"
        man1.install Dir["man/*.1"]
        generate_completions_from_executable(bin/"champrep", "completion")
      end
    end
  end

  test do
    system "#{bin}/champrep", "--version"
  end
end
